@extends('layouts.code-manager')
@section('title', 'Create Child for Parent')
@section('headerTitle', 'Assisted child creation')
@section('content')
<div><div class="flex items-center gap-2 text-xs font-medium text-slate-400"><a href="{{ route('code-manager.index') }}">Dashboard</a><span>/</span><span class="text-[#3c50e0]">Create Child for Parent</span></div><h1 class="mt-2 text-2xl font-semibold text-slate-800 sm:text-3xl">Create a child account for a parent</h1><p class="mt-2 text-sm text-slate-500">Find the parent, validate or create a licence code, then create and email the child login.</p></div>

<form method="POST" action="{{ route('code-manager.assisted-child.store') }}" class="mt-7 space-y-6" id="assisted-child-form">@csrf
<section class="rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 px-6 py-5"><p class="text-xs font-bold uppercase tracking-[.16em] text-indigo-600">Step 1</p><h2 class="mt-1 font-semibold text-slate-800">Find and select parent</h2></div><div class="p-6"><div class="flex flex-col gap-3 sm:flex-row"><input id="parent-search" class="min-w-0 flex-1 rounded-lg border-slate-300" placeholder="Search parent username or email" autocomplete="off"><button id="parent-search-button" type="button" class="rounded-lg bg-[#082c58] px-5 py-2.5 text-sm font-semibold text-white">Search parent</button></div><p id="parent-search-status" class="mt-2 text-xs text-slate-500">Enter at least 2 characters.</p><div id="parent-results" class="mt-4 grid gap-2"></div><input type="hidden" name="parent_id" id="parent-id" value="{{ old('parent_id') }}"><div id="selected-parent" class="mt-4 hidden rounded-xl border border-emerald-200 bg-emerald-50 p-4"><p class="text-xs font-bold uppercase tracking-wide text-emerald-700">Selected parent</p><p id="selected-parent-name" class="mt-1 font-semibold text-slate-800"></p><p id="selected-parent-detail" class="mt-1 text-sm text-slate-600"></p></div></div></section>

<section class="rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 px-6 py-5"><p class="text-xs font-bold uppercase tracking-[.16em] text-indigo-600">Step 2</p><h2 class="mt-1 font-semibold text-slate-800">Activation code and licence</h2></div><div class="space-y-5 p-6"><fieldset><legend class="text-sm font-semibold text-slate-700">Does the parent already have an activation code?</legend><div class="mt-3 flex flex-wrap gap-4"><label class="flex items-center gap-2 rounded-lg border border-slate-200 px-4 py-3 text-sm"><input type="radio" name="has_code" value="yes" @checked(old('has_code','yes')==='yes')> Yes, check existing code</label><label class="flex items-center gap-2 rounded-lg border border-slate-200 px-4 py-3 text-sm"><input type="radio" name="has_code" value="no" @checked(old('has_code')==='no')> No, generate automatically</label></div></fieldset>

<div id="existing-code-fields" class="rounded-xl border border-sky-200 bg-sky-50 p-4"><label class="block text-sm font-semibold text-slate-700">Activation code<div class="mt-2 flex flex-col gap-2 sm:flex-row"><input id="activation-code" name="activation_code" value="{{ old('activation_code') }}" class="min-w-0 flex-1 rounded-lg border-slate-300 font-mono uppercase" placeholder="HT-XXXX-XXXX-XXXX-XXXX-XXXX"><button id="check-code" type="button" class="rounded-lg bg-[#3c50e0] px-4 py-2.5 text-sm font-semibold text-white">Check code</button></div></label><p id="code-status" class="mt-2 text-sm text-slate-500">Select a parent first, then enter the code.</p></div>

<div id="automatic-code-fields" class="hidden grid gap-5 rounded-xl border border-violet-200 bg-violet-50 p-4 md:grid-cols-2"><label class="block text-sm font-semibold text-slate-700">Package<select name="package_id" id="assisted-package" class="mt-2 block w-full rounded-lg border-slate-300"><option value="">Select package</option>@foreach($packages as $package)<option value="{{ $package->id }}" @selected((int)old('package_id')===$package->id)>{{ $package->name }}</option>@endforeach</select></label><label class="block text-sm font-semibold text-slate-700">Duration<select name="duration_option_id" id="assisted-duration" class="mt-2 block w-full rounded-lg border-slate-300"><option value="">Select 6 or 12 months</option>@foreach($packages as $package)@foreach($package->durationOptions as $option)<option value="{{ $option->id }}" data-package="{{ $package->id }}" data-price="{{ $option->currency }} {{ number_format($option->price,2) }}" @selected((int)old('duration_option_id')===$option->id)>{{ $option->months }} months · {{ $option->currency }} {{ number_format($option->price,2) }}</option>@endforeach @endforeach</select></label><p class="text-xs text-violet-700 md:col-span-2">The code will use the parent company series, be redeemed immediately, and activate the selected duration.</p></div>
</div></section>

<section class="rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 px-6 py-5"><p class="text-xs font-bold uppercase tracking-[.16em] text-indigo-600">Step 3</p><h2 class="mt-1 font-semibold text-slate-800">Child account details</h2></div><div class="grid gap-5 p-6 md:grid-cols-2"><label class="block text-sm font-semibold text-slate-700">Child name<input name="name" value="{{ old('name') }}" required class="mt-2 block w-full rounded-lg border-slate-300"></label><label class="block text-sm font-semibold text-slate-700">Child standard / level<select name="level_id" id="assisted-level" required class="mt-2 block w-full rounded-lg border-slate-300"><option value="">Select code or package first</option>@foreach($levels as $level)<option value="{{ $level->id }}" data-level-option @selected((int)old('level_id')===$level->id)>{{ $level->name }}</option>@endforeach</select></label><label class="block text-sm font-semibold text-slate-700">Child username<input name="username" value="{{ old('username') }}" required minlength="4" maxlength="40" autocomplete="off" class="mt-2 block w-full rounded-lg border-slate-300"></label><div class="rounded-xl bg-slate-50 p-4 text-sm text-slate-600"><p class="font-semibold text-slate-700">Class name</p><p class="mt-1 text-xs leading-5">A temporary random class word will be assigned. The child can update it later.</p></div><label class="block text-sm font-semibold text-slate-700">Password<input name="password" type="password" required minlength="8" autocomplete="new-password" class="mt-2 block w-full rounded-lg border-slate-300"></label><label class="block text-sm font-semibold text-slate-700">Confirm password<input name="password_confirmation" type="password" required minlength="8" autocomplete="new-password" class="mt-2 block w-full rounded-lg border-slate-300"></label></div><div class="flex flex-col items-end gap-2 border-t border-slate-100 px-6 py-5"><button class="rounded-lg bg-[#3c50e0] px-6 py-3 text-sm font-semibold text-white">Create child, activate licence and email parent</button><p class="text-xs text-slate-400">The email includes username, password, name, standard, package, duration, and access dates.</p></div></section>
</form>
@endsection

@push('scripts')
<script>
document.addEventListener('DOMContentLoaded',()=>{
const csrf=document.querySelector('meta[name="csrf-token"]').content,parentId=document.getElementById('parent-id'),results=document.getElementById('parent-results'),searchStatus=document.getElementById('parent-search-status'),selected=document.getElementById('selected-parent'),selectedName=document.getElementById('selected-parent-name'),selectedDetail=document.getElementById('selected-parent-detail'),codeStatus=document.getElementById('code-status'),level=document.getElementById('assisted-level'),pkg=document.getElementById('assisted-package'),duration=document.getElementById('assisted-duration');
const showLevels=ids=>{const allowed=new Set(ids.map(String));level.querySelectorAll('[data-level-option]').forEach(option=>option.hidden=!allowed.has(option.value));if(!allowed.has(level.value))level.value=''};
document.getElementById('parent-search-button').addEventListener('click',async()=>{const q=document.getElementById('parent-search').value.trim();if(q.length<2){searchStatus.textContent='Enter at least 2 characters.';return}searchStatus.textContent='Searching…';results.innerHTML='';const response=await fetch(`${@json(route('code-manager.assisted-child.parents.search'))}?q=${encodeURIComponent(q)}`,{headers:{Accept:'application/json'}});const data=await response.json();searchStatus.textContent=data.parents?.length?`${data.parents.length} parent(s) found.`:'No parent found.';(data.parents||[]).forEach(parent=>{const button=document.createElement('button');button.type='button';button.className='rounded-xl border border-slate-200 p-4 text-left hover:border-[#3c50e0] hover:bg-indigo-50';button.innerHTML=`<span class="block font-semibold text-slate-800"></span><span class="mt-1 block text-sm text-slate-500"></span>`;button.children[0].textContent=parent.name;button.children[1].textContent=`${parent.username} · ${parent.email} · ${parent.company||'No company'}`;button.addEventListener('click',()=>{parentId.value=parent.id;selectedName.textContent=parent.name;selectedDetail.textContent=`${parent.username} · ${parent.email} · ${parent.company||'No company'}`;selected.classList.remove('hidden');results.innerHTML='';searchStatus.textContent='Parent selected.';codeStatus.textContent='Enter the activation code and click Check code.'});results.appendChild(button)})});
const syncMode=()=>{const hasCode=document.querySelector('input[name="has_code"]:checked').value==='yes';document.getElementById('existing-code-fields').classList.toggle('hidden',!hasCode);document.getElementById('automatic-code-fields').classList.toggle('hidden',hasCode);document.getElementById('activation-code').required=hasCode;pkg.required=!hasCode;duration.required=!hasCode;if(!hasCode)syncPackage()};document.querySelectorAll('input[name="has_code"]').forEach(input=>input.addEventListener('change',syncMode));
const syncPackage=()=>{const packageId=pkg.value;let durationValid=false;Array.from(duration.options).forEach((option,index)=>{if(!index)return;const visible=option.dataset.package===packageId;option.hidden=!visible;option.disabled=!visible;if(visible&&option.selected)durationValid=true});if(!durationValid)duration.value='';const packageData=@json($packages->mapWithKeys(fn($package)=>[(string)$package->id=>$package->levels->pluck('id')->values()]));showLevels(packageData[packageId]||[])};pkg.addEventListener('change',syncPackage);
document.getElementById('check-code').addEventListener('click',async()=>{if(!parentId.value){codeStatus.className='mt-2 text-sm text-rose-700';codeStatus.textContent='Select a parent first.';return}codeStatus.className='mt-2 text-sm text-slate-500';codeStatus.textContent='Checking code…';const response=await fetch(@json(route('code-manager.assisted-child.code.check')),{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json','X-CSRF-TOKEN':csrf},body:JSON.stringify({parent_id:parentId.value,activation_code:document.getElementById('activation-code').value})});const data=await response.json();if(!response.ok||!data.valid){codeStatus.className='mt-2 text-sm text-rose-700';codeStatus.textContent='Code is invalid, expired, used, or not available for this parent.';showLevels([]);return}showLevels(data.levels.map(item=>item.id));codeStatus.className='mt-2 text-sm font-semibold text-emerald-700';codeStatus.textContent=`Valid: ${data.package.name} · ${data.duration_months} months`});
syncMode();syncPackage();
});
</script>
@endpush
