@extends('layouts.code-manager')
@section('title', 'Bulk Generate')
@section('content')
<div class="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><div class="flex items-center gap-2 text-xs font-medium text-slate-400"><a href="{{ route('code-manager.index') }}">Dashboard</a><span>/</span><span class="text-[#3c50e0]">Bulk Generate</span></div><h1 class="mt-2 text-2xl font-semibold text-slate-800 sm:text-3xl">Bulk activation-code generation</h1><p class="mt-2 text-sm text-slate-500">Create controlled company or event batches and distribute them through CSV.</p></div><span class="w-fit rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-xs font-semibold text-amber-700">Codes are not emailed automatically</span></div>

<div class="mt-7 grid gap-6 xl:grid-cols-[390px_1fr]">
<section class="h-fit rounded-2xl border border-slate-200 bg-white shadow-sm xl:sticky xl:top-24"><div class="border-b border-slate-200 px-6 py-5"><h2 class="font-semibold text-slate-800">New code batch</h2><p class="mt-1 text-xs text-slate-500">Generate 10, 100, or 1,000 single-use codes.</p></div>
<form method="POST" action="{{ route('code-manager.batches.store') }}" class="space-y-4 p-6" id="bulk-page-form">@csrf<input type="hidden" name="return_to" value="bulk">
<label class="block text-sm font-medium text-slate-700">Generate for<select name="source_type" id="bulk-page-source" required class="mt-2 block w-full rounded-lg border-slate-300"><option value="company" @selected(old('source_type') === 'company')>Company</option><option value="event" @selected(old('source_type') === 'event')>Event</option></select></label>
<label id="bulk-page-company-field" class="block text-sm font-medium text-slate-700">Company<select name="company_id" class="mt-2 block w-full rounded-lg border-slate-300"><option value="">Select company</option>@foreach($companies as $company)<option value="{{ $company->id }}" @selected((int)old('company_id') === $company->id)>{{ $company->name }}{{ $company->reference_code ? ' · '.$company->reference_code : '' }}</option>@endforeach</select><span class="mt-1.5 block text-xs font-normal text-slate-500">Identifies the campaign and code series. All parents can redeem these codes.</span></label>
<label id="bulk-page-event-field" class="hidden text-sm font-medium text-slate-700">Event name<input name="event_name" value="{{ old('event_name') }}" maxlength="255" class="mt-2 block w-full rounded-lg border-slate-300" placeholder="Education Expo 2026"><span class="mt-1.5 block text-xs font-normal text-slate-500">Event codes can be redeemed by any parent.</span></label>
<label class="block text-sm font-medium text-slate-700">Code series<input name="series_prefix" value="{{ old('series_prefix', 'HT') }}" required maxlength="20" pattern="[A-Za-z0-9]+" class="mt-2 block w-full rounded-lg border-slate-300 uppercase" placeholder="Example: EXPO26"><span class="mt-1.5 block text-xs font-normal text-slate-500">Use HT for Dasar Jati, XCLN for Explode, or a dedicated series for this event.</span></label>
<label class="block text-sm font-medium text-slate-700">Package<select name="package_id" id="bulk-page-package" required class="mt-2 block w-full rounded-lg border-slate-300"><option value="">Select package</option>@foreach($packages as $package)<option value="{{ $package->id }}" @selected((int)old('package_id') === $package->id)>{{ $package->name }}</option>@endforeach</select></label>
<div class="grid grid-cols-2 gap-3"><label class="block text-sm font-medium text-slate-700">Licence duration (months)<input name="duration_months" type="number" min="1" max="120" step="1" inputmode="numeric" value="{{ old('duration_months', 6) }}" required class="mt-2 block w-full rounded-lg border-slate-300"><span class="mt-1.5 block text-xs font-normal text-slate-500">Also sets the code expiry period.</span></label><label class="block text-sm font-medium text-slate-700">Quantity<input name="quantity" type="number" min="1" max="10000" step="1" inputmode="numeric" value="{{ old('quantity', 10) }}" required class="mt-2 block w-full rounded-lg border-slate-300"></label></div>
<button class="w-full rounded-lg bg-[#3c50e0] px-4 py-3 text-sm font-semibold text-white shadow-sm hover:bg-[#3345c6]">Generate code batch</button>
</form></section>

<section class="min-w-0 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b border-slate-200 px-6 py-5"><div><h2 class="font-semibold text-slate-800">Batch history</h2><p class="mt-1 text-xs text-slate-500">Usage and export history for company and event campaigns.</p></div><span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-500">{{ $batches->total() }} batches</span></div><div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead><tr class="border-b border-slate-100 text-xs font-medium text-slate-400"><th class="px-5 py-3">Batch / source</th><th class="px-5 py-3">Package</th><th class="px-5 py-3">Usage</th><th class="px-5 py-3">Expiry</th><th class="px-5 py-3">Created by</th><th class="px-5 py-3">Action</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($batches as $batch)<tr class="align-top hover:bg-slate-50/70"><td class="px-5 py-4"><p class="font-mono text-xs font-semibold text-slate-700">{{ $batch->reference }}</p><p class="mt-1 font-medium text-slate-800">{{ $batch->company?->name ?? $batch->event_name }}</p><span class="mt-2 inline-flex rounded-full bg-indigo-50 px-2 py-1 text-[10px] font-semibold text-[#3c50e0]">{{ $batch->series_prefix }}</span><span class="mt-2 inline-flex rounded-full bg-slate-100 px-2 py-1 text-[10px] font-semibold capitalize text-slate-600">{{ $batch->source_type }}</span></td><td class="px-5 py-4"><p class="font-medium text-slate-700">{{ $batch->package->name }}</p><p class="mt-1 text-xs text-slate-400">{{ $batch->durationOption?->months }} months</p></td><td class="px-5 py-4"><p class="font-semibold text-slate-700">{{ number_format($batch->activation_codes_count) }} total</p><div class="mt-2 flex gap-2 text-[10px]"><span class="rounded-full bg-amber-50 px-2 py-1 font-semibold text-amber-700">{{ $batch->unused_codes_count }} unused</span><span class="rounded-full bg-emerald-50 px-2 py-1 font-semibold text-emerald-700">{{ $batch->redeemed_codes_count }} used</span></div></td><td class="whitespace-nowrap px-5 py-4 text-slate-500">{{ $batch->expires_at?->format('d M Y') }}</td><td class="px-5 py-4"><p class="font-medium text-slate-700">{{ $batch->creator?->name ?? 'System' }}</p><p class="mt-1 text-xs text-slate-400">{{ $batch->created_at->format('d M Y H:i') }}</p></td><td class="px-5 py-4"><a href="{{ route('code-manager.batches.export',$batch) }}" class="inline-flex rounded-lg border border-slate-300 px-3 py-2 text-xs font-semibold text-slate-600 hover:border-[#3c50e0] hover:text-[#3c50e0]">Export CSV</a></td></tr>@empty<tr><td colspan="6" class="p-10 text-center text-slate-500">No bulk batches generated yet.</td></tr>@endforelse</tbody></table></div>@if($batches->hasPages())<div class="border-t border-slate-200 p-5">{{ $batches->links() }}</div>@endif</section>
</div>
@endsection
@push('scripts')
<script>(()=>{const source=document.getElementById('bulk-page-source'),companyField=document.getElementById('bulk-page-company-field'),eventField=document.getElementById('bulk-page-event-field'),company=companyField.querySelector('select'),event=eventField.querySelector('input');function syncSource(){const isCompany=source.value==='company';companyField.classList.toggle('hidden',!isCompany);eventField.classList.toggle('hidden',isCompany);company.required=isCompany;event.required=!isCompany}source.addEventListener('change',syncSource);syncSource()})();</script>
@endpush
