@extends('layouts.code-manager')
@section('title', 'Per-person Generate')
@section('content')
<div class="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><div class="flex items-center gap-2 text-xs font-medium text-slate-400"><a href="{{ route('code-manager.index') }}">Dashboard</a><span>/</span><span class="text-[#3c50e0]">Per-person Generate</span></div><h1 class="mt-2 text-2xl font-semibold text-slate-800 sm:text-3xl">Generate a personal activation code</h1><p class="mt-2 text-sm text-slate-500">Issue one code to a specific parent for a new child or a selected child renewal.</p></div></div>

<div class="mt-7 grid gap-6 xl:grid-cols-[minmax(0,720px)_1fr]">
<section class="rounded-2xl border border-slate-200 bg-white shadow-sm">
    <div class="border-b border-slate-200 px-6 py-5"><div class="flex items-center gap-3"><span class="flex h-11 w-11 items-center justify-center rounded-full bg-indigo-50 text-[#3c50e0]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" class="h-5 w-5"><circle cx="9" cy="8" r="3"/><path d="M3 20a6 6 0 0 1 12 0M16 8h5M18.5 5.5v5"/></svg></span><div><h2 class="font-semibold text-slate-800">Parent and licence details</h2><p class="mt-0.5 text-xs text-slate-500">The activation code will be sent to the parent email.</p></div></div></div>
    <form method="POST" action="{{ route('code-manager.codes.store') }}" enctype="multipart/form-data" class="grid gap-5 p-6 sm:grid-cols-2" id="individual-code-form">@csrf<input type="hidden" name="return_to" value="individual">
        <label class="block text-sm font-medium text-slate-700">Use for<select name="intended_use" id="individual-purpose" required class="mt-2 block w-full rounded-lg border-slate-300 focus:border-[#3c50e0] focus:ring-[#3c50e0]"><option value="new" @selected(old('intended_use') === 'new')>New child account</option><option value="renewal" @selected(old('intended_use') === 'renewal')>Renew existing child</option></select></label>
        <label class="block text-sm font-medium text-slate-700">Package<select name="package_id" id="individual-package" required class="mt-2 block w-full rounded-lg border-slate-300 focus:border-[#3c50e0] focus:ring-[#3c50e0]"><option value="">Select package</option>@foreach($packages as $package)<option value="{{ $package->id }}" @selected((int)old('package_id') === $package->id)>{{ $package->name }}</option>@endforeach</select></label>
        <label class="block text-sm font-medium text-slate-700">Licence duration<select name="duration_option_id" id="individual-duration" required class="mt-2 block w-full rounded-lg border-slate-300 focus:border-[#3c50e0] focus:ring-[#3c50e0]"><option value="">Select duration</option>@foreach($packages as $package)@foreach($package->durationOptions as $option)<option value="{{ $option->id }}" data-package="{{ $package->id }}" data-price="{{ number_format($option->price, 2, '.', '') }}" data-currency="{{ $option->currency }}" @selected((int)old('duration_option_id') === $option->id)>{{ $option->months }} months</option>@endforeach @endforeach</select></label>
        <label class="block text-sm font-medium text-slate-700 sm:col-span-2">Price<input id="individual-price" readonly value="Select a package and duration" class="mt-2 block w-full rounded-lg border-slate-200 bg-slate-50 text-slate-600"></label>
        <label class="block text-sm font-medium text-slate-700 sm:col-span-2">Parent email or username<input name="parent_login" value="{{ old('parent_login') }}" required class="mt-2 block w-full rounded-lg border-slate-300 focus:border-[#3c50e0] focus:ring-[#3c50e0]" placeholder="parent@example.com"></label>
        <label id="individual-child-field" class="hidden text-sm font-medium text-slate-700 sm:col-span-2">Child username<input name="child_login" value="{{ old('child_login') }}" class="mt-2 block w-full rounded-lg border-slate-300 focus:border-[#3c50e0] focus:ring-[#3c50e0]" placeholder="student_username"><span class="mt-1.5 block text-xs font-normal text-slate-500">The renewal code will be locked to this child.</span></label>
        <label class="block text-sm font-medium text-slate-700 sm:col-span-2">Reason or reference<textarea name="generation_reason" required rows="4" maxlength="1000" class="mt-2 block w-full rounded-lg border-slate-300 focus:border-[#3c50e0] focus:ring-[#3c50e0]" placeholder="Payment reference, WhatsApp request, or internal note">{{ old('generation_reason') }}</textarea></label>
        <label class="block text-sm font-medium text-slate-700 sm:col-span-2">Upload receipt <span class="font-normal text-slate-400">(optional)</span><input name="receipt" type="file" accept=".pdf,.jpg,.jpeg,.png" class="mt-2 block w-full rounded-lg border border-slate-300 text-sm text-slate-600 file:mr-4 file:border-0 file:bg-indigo-50 file:px-4 file:py-2 file:text-sm file:font-semibold file:text-[#3c50e0]"><span class="mt-1.5 block text-xs font-normal text-slate-500">PDF, JPG, or PNG only; maximum 5 MB. It is stored with this code’s audit record.</span></label>
        <div class="flex justify-end gap-3 border-t border-slate-100 pt-5 sm:col-span-2"><a href="{{ route('code-manager.index') }}" class="rounded-lg border border-slate-300 px-5 py-2.5 text-sm font-semibold text-slate-600">Cancel</a><button class="rounded-lg bg-[#3c50e0] px-5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-[#3345c6]">Generate and email code</button></div>
    </form>
</section>

<aside class="space-y-5"><section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="font-semibold text-slate-800">How this works</h2><ol class="mt-5 space-y-5">@foreach([['1','Find the parent','Use the registered email address or username.'],['2','Choose the purpose','New-child codes create an account; renewal codes extend one child.'],['3','Deliver securely','The code is emailed and remains visible in the code register until used.']] as [$number,$title,$copy])<li class="flex gap-3"><span class="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-indigo-50 text-xs font-bold text-[#3c50e0]">{{ $number }}</span><div><p class="text-sm font-semibold text-slate-700">{{ $title }}</p><p class="mt-1 text-xs leading-5 text-slate-500">{{ $copy }}</p></div></li>@endforeach</ol></section><section class="rounded-2xl border border-amber-200 bg-amber-50 p-5"><p class="text-sm font-semibold text-amber-800">Audit reminder</p><p class="mt-1 text-xs leading-5 text-amber-700">Always include a payment or contact reference so another manager can understand why the code was issued.</p></section></aside>
</div>
@endsection
@push('scripts')
<script>(()=>{const purpose=document.getElementById('individual-purpose'),field=document.getElementById('individual-child-field'),input=field.querySelector('input'),pkg=document.getElementById('individual-package'),duration=document.getElementById('individual-duration'),price=document.getElementById('individual-price');function sync(){const renewal=purpose.value==='renewal';field.classList.toggle('hidden',!renewal);input.required=renewal}function syncDuration(){let valid=false;Array.from(duration.options).forEach((option,index)=>{if(!index)return;const visible=option.dataset.package===pkg.value;option.hidden=!visible;option.disabled=!visible;if(visible&&option.selected)valid=true});if(!valid)duration.value='';syncPrice()}function syncPrice(){const option=duration.options[duration.selectedIndex];price.value=option&&option.dataset.price ? `${option.dataset.currency} ${Number(option.dataset.price).toFixed(2)}` : 'Select a package and duration'}purpose.addEventListener('change',sync);pkg.addEventListener('change',syncDuration);duration.addEventListener('change',syncPrice);sync();syncDuration()})();</script>
@endpush
