@extends('layouts.code-manager')
@section('title', 'Code Register')
@section('headerTitle', 'Activation-code register')
@section('content')
<div class="flex items-end justify-between gap-4"><div><div class="flex items-center gap-2 text-xs font-medium text-slate-400"><a href="{{ route('code-manager.index') }}">Dashboard</a><span>/</span><span class="text-[#3c50e0]">Code Register</span></div><h1 class="mt-2 text-2xl font-semibold text-slate-800 sm:text-3xl">Activation-code register</h1><p class="mt-2 text-sm text-slate-500">Search, review, and manage every activation code.</p></div><a href="{{ route('code-manager.individual.index') }}" class="rounded-lg bg-[#3c50e0] px-4 py-2.5 text-sm font-semibold text-white">Generate personal code</a></div>

<div class="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
@foreach([['Total codes',$stats['total'],'text-[#3c50e0]'],['Not used',$stats['unused'],'text-amber-600'],['Redeemed',$stats['redeemed'],'text-emerald-600'],['Renewals',$stats['renewal'],'text-violet-600']] as [$label,$value,$colour])
<article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm font-medium text-slate-500">{{ $label }}</p><p class="mt-2 text-2xl font-semibold {{ $colour }}">{{ number_format($value) }}</p></article>
@endforeach
</div>

<section class="mt-6 min-w-0 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
<form method="GET" class="grid gap-3 border-b border-slate-200 p-5 md:grid-cols-2 xl:grid-cols-4">
<label class="xl:col-span-2"><span class="mb-1 block text-xs font-semibold text-slate-500">Search</span><input name="search" value="{{ $filters['search'] ?? '' }}" class="w-full rounded-lg border-slate-300 py-2.5 text-sm" placeholder="Full code, last 4, parent, child, package, batch, reason, or creator"><span class="mt-1 block text-[11px] text-slate-400">Code search accepts uppercase, lowercase, with or without hyphens.</span></label>
<label><span class="mb-1 block text-xs font-semibold text-slate-500">Status</span><select name="status" class="w-full rounded-lg border-slate-300 text-sm"><option value="">All statuses</option>@foreach(['unused'=>'Not used','redeemed'=>'Redeemed','revoked'=>'Revoked','expired'=>'Expired'] as $value=>$label)<option value="{{ $value }}" @selected(($filters['status']??'')===$value)>{{ $label }}</option>@endforeach</select></label>
<label><span class="mb-1 block text-xs font-semibold text-slate-500">Type</span><select name="intended_use" class="w-full rounded-lg border-slate-300 text-sm"><option value="">All types</option><option value="new" @selected(($filters['intended_use']??'')==='new')>New child</option><option value="renewal" @selected(($filters['intended_use']??'')==='renewal')>Renewal</option><option value="any" @selected(($filters['intended_use']??'')==='any')>Legacy / any</option></select></label>
<label><span class="mb-1 block text-xs font-semibold text-slate-500">Package</span><select name="package_id" class="w-full rounded-lg border-slate-300 text-sm"><option value="">All packages</option>@foreach($packages as $package)<option value="{{ $package->id }}" @selected((int)($filters['package_id']??0)===$package->id)>{{ $package->name }}</option>@endforeach</select></label>
<label><span class="mb-1 block text-xs font-semibold text-slate-500">Code series</span><select name="series_prefix" class="w-full rounded-lg border-slate-300 text-sm"><option value="">All series</option>@foreach($seriesPrefixes as $series)<option value="{{ $series }}" @selected(($filters['series_prefix']??'')===$series)>{{ $series }}</option>@endforeach</select></label>
<label><span class="mb-1 block text-xs font-semibold text-slate-500">Source</span><select name="source" class="w-full rounded-lg border-slate-300 text-sm"><option value="">All sources</option>@foreach($sources as $source)<option value="{{ $source }}" @selected(($filters['source']??'')===$source)>{{ ucfirst(str_replace('_', ' ', $source)) }}</option>@endforeach</select></label>
<div class="flex items-end gap-2"><button class="flex-1 rounded-lg bg-[#3c50e0] px-4 py-2.5 text-sm font-semibold text-white">Apply filters</button><a href="{{ route('code-manager.register.index') }}" class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-600">Reset</a></div>
<label><span class="mb-1 block text-xs font-semibold text-slate-500">Generated from</span><input name="created_from" type="date" value="{{ $filters['created_from'] ?? '' }}" class="w-full rounded-lg border-slate-300 text-sm"></label>
<label><span class="mb-1 block text-xs font-semibold text-slate-500">Generated to</span><input name="created_to" type="date" value="{{ $filters['created_to'] ?? '' }}" class="w-full rounded-lg border-slate-300 text-sm"></label>
<label><span class="mb-1 block text-xs font-semibold text-slate-500">Expires from</span><input name="expires_from" type="date" value="{{ $filters['expires_from'] ?? '' }}" class="w-full rounded-lg border-slate-300 text-sm"></label>
<label><span class="mb-1 block text-xs font-semibold text-slate-500">Expires to</span><input name="expires_to" type="date" value="{{ $filters['expires_to'] ?? '' }}" class="w-full rounded-lg border-slate-300 text-sm"></label>
</form>

<div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead><tr class="border-b border-slate-100 bg-slate-50/70 text-xs font-medium text-slate-500"><th class="px-5 py-3.5">Code</th><th class="px-5 py-3.5">Parent / Source</th><th class="px-5 py-3.5">Package & duration</th><th class="px-5 py-3.5">Validity dates</th><th class="px-5 py-3.5">Status</th><th class="px-5 py-3.5 text-center">Actions</th></tr></thead><tbody class="divide-y divide-slate-100">
@forelse($codes as $code)
@php($openRequest=$code->licenseAdjustmentRequests->first(fn($item)=>$item->isOpen()))
@php($months=data_get($code->metadata, 'duration_months'))
<tr class="hover:bg-slate-50/70"><td class="whitespace-nowrap px-5 py-4"><p class="font-mono text-xs font-semibold text-slate-700">{{ $code->status==='unused' ? $code->code_value : $code->series_prefix.'-****-****-'.$code->code_last_four }}</p><span class="mt-1 inline-flex rounded bg-indigo-50 px-1.5 py-0.5 text-[10px] font-bold text-indigo-700">{{ $code->series_prefix }}</span></td><td class="px-5 py-4"><p class="font-medium text-slate-700">{{ $code->purchaser?->name ?? $code->batch?->company?->name ?? $code->batch?->event_name ?? 'Unassigned' }}</p><p class="mt-0.5 text-[11px] text-slate-400">{{ $code->purchaser?->email ?? $code->batch?->reference ?? ucfirst(str_replace('_',' ',$code->source)) }}</p><p class="mt-1 text-[11px] text-slate-500">Created {{ $code->created_at->format('d M Y, H:i') }}</p></td><td class="whitespace-nowrap px-5 py-4"><p class="font-medium text-slate-700">{{ $code->package->name }}</p><p class="mt-0.5 text-[11px] text-slate-500">{{ $months ? $months.' months' : $code->duration_days.' days' }}</p><p class="mt-0.5 text-[11px] text-slate-400">{{ $code->purchase_amount ? $code->package->currency.' '.number_format($code->purchase_amount, 2) : 'No price recorded' }}</p></td><td class="whitespace-nowrap px-5 py-4 text-xs"><p class="text-slate-600">Code expires: {{ $code->expires_at?->format('d M Y') ?? 'No expiry' }}</p>@if($code->subscription)<p class="mt-1 text-emerald-700">Licence: {{ $code->subscription->starts_at->format('d M Y') }} – {{ $code->subscription->ends_at->format('d M Y') }}</p>@else<p class="mt-1 text-slate-400">Licence starts on redemption</p>@endif</td><td class="px-5 py-4"><span class="inline-flex rounded-full px-2.5 py-1 text-[11px] font-semibold {{ $code->status==='redeemed'?'bg-emerald-50 text-emerald-700':($code->status==='unused'?'bg-amber-50 text-amber-700':'bg-violet-50 text-violet-700') }}">{{ $code->status==='unused'?'Not used':ucfirst($code->status) }}</span>@if($openRequest)<p class="mt-1 text-[10px] font-semibold capitalize text-rose-600">{{ $openRequest->type }} {{ str_replace('_',' ',$openRequest->status) }}</p>@endif</td><td class="px-5 py-4 text-center">@if($code->status==='unused')<div class="mb-2 inline-flex flex-col items-center gap-2"><form method="POST" action="{{ route('code-manager.codes.resend',$code->uuid) }}">@csrf<button class="text-xs font-semibold text-[#3c50e0]">Resend email</button></form><form method="POST" action="{{ route('code-manager.codes.revoke',$code->uuid) }}" onsubmit="return confirm('Revoke this unused code?')">@csrf<input type="hidden" name="reason" value="Revoked by code manager {{ auth()->user()->username }}"><button class="text-xs font-semibold text-rose-600">Revoke</button></form></div>@endif @include('code-manager.partials.adjustment-action', ['code' => $code, 'openRequest' => $openRequest])</td></tr>
@empty<tr><td colspan="6" class="p-10 text-center text-slate-500">No activation codes match these filters.</td></tr>@endforelse
</tbody></table></div>
<div class="flex flex-col items-center justify-between gap-3 border-t border-slate-200 px-5 py-4 sm:flex-row"><p class="text-xs text-slate-500">Showing {{ $codes->firstItem()??0 }} to {{ $codes->lastItem()??0 }} of {{ number_format($codes->total()) }} results</p>{{ $codes->onEachSide(1)->links() }}</div>
</section>
@endsection
