<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}">
    <title>@yield('title', 'Code Manager') · HomeTutor</title>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Outfit:wght@400;500;600;700&display=swap" rel="stylesheet">
    @vite('resources/css/app.css')
</head>
<body class="min-h-screen bg-[#f7f9fc] font-sans text-slate-700 antialiased">
<div class="min-h-screen lg:flex">
    <div id="sidebar-overlay" class="fixed inset-0 z-40 hidden bg-slate-950/50 backdrop-blur-sm lg:hidden"></div>
    <aside id="code-sidebar" class="fixed inset-y-0 left-0 z-50 flex w-[290px] -translate-x-full flex-col bg-[#1c2434] text-slate-300 shadow-2xl transition-all duration-300 lg:sticky lg:top-0 lg:h-screen lg:translate-x-0 lg:shadow-none">
        <div class="flex h-[76px] items-center justify-between border-b border-white/10 px-6">
            <a href="{{ route('code-manager.index') }}" data-sidebar-item class="flex items-center gap-3"><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#3c50e0] text-white shadow-lg shadow-indigo-950/40"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" class="h-6 w-6"><path stroke-linecap="round" stroke-linejoin="round" d="M4 5h16a1 1 0 0 1 1 1v3a3 3 0 0 0 0 6v3a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1v-3a3 3 0 0 0 0-6V6a1 1 0 0 1 1-1Z"/><path d="M12 8v8" stroke-dasharray="2 2"/></svg></span><span data-sidebar-label><span class="block text-lg font-bold tracking-wide text-white">HomeTutor</span><span class="block text-[11px] font-semibold uppercase tracking-[.18em] text-slate-400">Code Manager</span></span></a>
            <button id="sidebar-close" class="rounded-lg p-2 text-slate-400 hover:bg-white/10 hover:text-white lg:hidden" aria-label="Close navigation">✕</button>
        </div>
        <nav class="flex-1 overflow-y-auto px-4 py-6">
            <p data-sidebar-label class="px-3 text-[11px] font-semibold uppercase tracking-[.18em] text-slate-500">Menu</p>
            <div class="mt-3 space-y-1.5 text-sm font-medium">
                <a href="{{ route('code-manager.index') }}" data-sidebar-item class="sidebar-link flex items-center gap-3 rounded-lg px-4 py-3 {{ request()->routeIs('code-manager.index') ? 'bg-[#333a48] text-white' : 'hover:bg-[#333a48] hover:text-white' }}"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" class="h-5 w-5 shrink-0"><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></svg><span data-sidebar-label>Dashboard</span></a>
                <a href="{{ route('code-manager.individual.index') }}" data-sidebar-item class="sidebar-link flex items-center gap-3 rounded-lg px-4 py-3 transition {{ request()->routeIs('code-manager.individual.*') ? 'bg-[#333a48] text-white' : 'hover:bg-[#333a48] hover:text-white' }}"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" class="h-5 w-5 shrink-0"><circle cx="9" cy="8" r="3"/><path d="M3 20a6 6 0 0 1 12 0M16 8h5M18.5 5.5v5"/></svg><span data-sidebar-label>Per-person Generate</span></a>
                <a href="{{ route('code-manager.assisted-child.create') }}" data-sidebar-item class="sidebar-link flex items-center gap-3 rounded-lg px-4 py-3 transition {{ request()->routeIs('code-manager.assisted-child.*') ? 'bg-[#333a48] text-white' : 'hover:bg-[#333a48] hover:text-white' }}"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" class="h-5 w-5 shrink-0"><circle cx="9" cy="8" r="3"/><path d="M3 20a6 6 0 0 1 12 0M17 11v6M14 14h6"/></svg><span data-sidebar-label>Create Child for Parent</span></a>
                <a href="{{ route('code-manager.bulk.index') }}" data-sidebar-item class="sidebar-link flex items-center gap-3 rounded-lg px-4 py-3 transition {{ request()->routeIs('code-manager.bulk.*') ? 'bg-[#333a48] text-white' : 'hover:bg-[#333a48] hover:text-white' }}"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" class="h-5 w-5 shrink-0"><path d="M4 7h16M4 12h16M4 17h10"/><circle cx="18" cy="17" r="3"/></svg><span data-sidebar-label>Bulk Generate</span></a>
                <a href="{{ route('code-manager.register.index') }}" data-sidebar-item class="sidebar-link flex items-center gap-3 rounded-lg px-4 py-3 transition {{ request()->routeIs('code-manager.register.*') ? 'bg-[#333a48] text-white' : 'hover:bg-[#333a48] hover:text-white' }}"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" class="h-5 w-5 shrink-0"><path d="M4 4h16v16H4zM8 9h8M8 13h8M8 17h5"/></svg><span data-sidebar-label>Code Register</span></a>
            </div>
            <p data-sidebar-label class="mt-8 px-3 text-[11px] font-semibold uppercase tracking-[.18em] text-slate-500">Account</p>
            <button type="button" data-password-open data-sidebar-item class="mt-3 flex w-full items-center gap-3 rounded-lg px-4 py-3 text-left text-sm font-medium transition hover:bg-[#333a48] hover:text-white"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" class="h-5 w-5 shrink-0"><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></svg><span data-sidebar-label>Profile & password</span></button>
        </nav>
        <div class="border-t border-white/10 p-4"><button id="sidebar-collapse" class="mb-3 hidden h-10 w-10 items-center justify-center rounded-full bg-[#2d3748] text-slate-300 hover:bg-[#3c50e0] hover:text-white lg:flex" aria-label="Collapse sidebar"><svg id="sidebar-collapse-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" class="h-5 w-5"><path d="m15 18-6-6 6-6M20 18l-6-6 6-6"/></svg></button><div data-sidebar-profile class="rounded-xl bg-[#252d3d] p-4"><p class="truncate text-sm font-semibold text-white">{{ auth()->user()->name }}</p><p class="mt-0.5 truncate text-xs text-slate-400">{{ auth()->user()->username }}</p><form method="POST" action="{{ route('logout') }}" class="mt-3">@csrf<button class="w-full rounded-lg border border-white/10 px-3 py-2 text-xs font-semibold text-slate-300 hover:bg-white/10 hover:text-white">Sign out</button></form></div></div>
    </aside>

    <div class="min-w-0 flex-1">
        <header class="sticky top-0 z-30 flex h-[76px] items-center justify-between border-b border-slate-200 bg-white/95 px-4 backdrop-blur sm:px-6 xl:px-8">
            <div class="flex items-center gap-3"><button id="sidebar-open" class="rounded-lg border border-slate-200 p-2.5 text-slate-600 hover:bg-slate-50" aria-label="Toggle navigation"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" class="h-5 w-5"><path d="M4 6h16M4 12h16M4 18h16"/></svg></button><div><p class="text-sm font-semibold text-slate-800">@yield('headerTitle', 'Licence operations')</p><p class="hidden text-xs text-slate-400 sm:block">Manage activation-code inventory and distribution</p></div></div>
            <div class="flex items-center gap-3"><span class="hidden rounded-lg bg-slate-100 px-3 py-2 text-xs font-medium text-slate-500 md:block">{{ now()->format('d M Y, H:i') }}</span><button type="button" data-password-open class="flex items-center gap-2 rounded-full border border-slate-200 bg-white p-1.5 pr-3 hover:bg-slate-50"><span class="flex h-8 w-8 items-center justify-center rounded-full bg-[#3c50e0] text-xs font-bold text-white">{{ Str::upper(Str::substr(auth()->user()->name, 0, 1)) }}</span><span class="hidden text-left sm:block"><span class="block max-w-28 truncate text-xs font-semibold text-slate-700">{{ auth()->user()->name }}</span><span class="block text-[10px] text-slate-400">Code Manager</span></span></button></div>
        </header>
        <main class="p-4 sm:p-6 xl:p-8">
            @if(session('success'))<div class="mb-5 flex items-start gap-3 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-800"><span class="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-emerald-500 text-xs text-white">✓</span>{{ session('success') }}</div>@endif
            @if(session('error'))<div class="mb-5 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-800">{{ session('error') }}</div>@endif
            @if($errors->any())<div class="mb-5 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-800"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
            @yield('content')
        </main>
    </div>
</div>

<div id="password-modal" class="fixed inset-0 z-[70] hidden items-center justify-center bg-slate-950/50 p-4 backdrop-blur-sm"><div class="w-full max-w-md rounded-2xl bg-white shadow-2xl"><div class="flex items-center justify-between border-b border-slate-200 px-6 py-5"><div><h2 class="font-semibold text-slate-800">Change password</h2><p class="mt-1 text-xs text-slate-500">Use at least 10 characters.</p></div><button type="button" data-password-close class="rounded-lg p-2 text-slate-400 hover:bg-slate-100">✕</button></div><form method="POST" action="{{ route('code-manager.password.update') }}" class="space-y-4 p-6">@csrf @method('PUT')<label class="block text-sm font-medium text-slate-700">Current password<input type="password" name="current_password" required class="mt-2 block w-full rounded-lg border-slate-300"></label><label class="block text-sm font-medium text-slate-700">New password<input type="password" name="password" required class="mt-2 block w-full rounded-lg border-slate-300"></label><label class="block text-sm font-medium text-slate-700">Confirm new password<input type="password" name="password_confirmation" required class="mt-2 block w-full rounded-lg border-slate-300"></label><div class="flex justify-end gap-3 pt-2"><button type="button" data-password-close class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold">Cancel</button><button class="rounded-lg bg-[#3c50e0] px-4 py-2.5 text-sm font-semibold text-white hover:bg-[#3345c6]">Update password</button></div></form></div></div>

<script>(()=>{const sidebar=document.getElementById('code-sidebar'),overlay=document.getElementById('sidebar-overlay'),collapseButton=document.getElementById('sidebar-collapse'),collapseIcon=document.getElementById('sidebar-collapse-icon');let collapsed=false;try{collapsed=localStorage.getItem('code-manager-sidebar-collapsed')==='1'}catch(_){}const applyCollapsed=value=>{collapsed=value;sidebar.classList.toggle('lg:w-[88px]',value);document.querySelectorAll('[data-sidebar-label]').forEach(item=>item.classList.toggle('lg:hidden',value));document.querySelectorAll('[data-sidebar-item]').forEach(item=>item.classList.toggle('lg:justify-center',value));document.querySelector('[data-sidebar-profile]')?.classList.toggle('lg:hidden',value);collapseIcon?.classList.toggle('rotate-180',value);collapseButton?.setAttribute('aria-label',value?'Expand sidebar':'Collapse sidebar');try{localStorage.setItem('code-manager-sidebar-collapsed',value?'1':'0')}catch(_){}};applyCollapsed(collapsed);const openMobile=()=>{sidebar.classList.remove('-translate-x-full');overlay.classList.remove('hidden')};const closeMobile=()=>{sidebar.classList.add('-translate-x-full');overlay.classList.add('hidden')};document.getElementById('sidebar-open')?.addEventListener('click',()=>window.innerWidth>=1024?applyCollapsed(!collapsed):openMobile());collapseButton?.addEventListener('click',()=>applyCollapsed(!collapsed));document.getElementById('sidebar-close')?.addEventListener('click',closeMobile);overlay?.addEventListener('click',closeMobile);document.querySelectorAll('.sidebar-link').forEach(link=>link.addEventListener('click',()=>{if(window.innerWidth<1024)closeMobile()}));const modal=document.getElementById('password-modal');document.querySelectorAll('[data-password-open]').forEach(button=>button.addEventListener('click',()=>{modal.classList.remove('hidden');modal.classList.add('flex')}));document.querySelectorAll('[data-password-close]').forEach(button=>button.addEventListener('click',()=>{modal.classList.add('hidden');modal.classList.remove('flex')}));modal.addEventListener('click',event=>{if(event.target===modal){modal.classList.add('hidden');modal.classList.remove('flex')}})})();</script>
@stack('scripts')
</body>
</html>
